export const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  OPERATIONS_ADMIN: 'OPERATIONS_ADMIN',
  FINANCE_ADMIN: 'FINANCE_ADMIN',
  SUPPORT_ADMIN: 'SUPPORT_ADMIN',
}

export const ROLE_LABELS = {
  [ROLES.SUPER_ADMIN]: 'Super Admin',
  [ROLES.OPERATIONS_ADMIN]: 'Operations Admin',
  [ROLES.FINANCE_ADMIN]: 'Finance Admin',
  [ROLES.SUPPORT_ADMIN]: 'Support Admin',
}

export const PERMISSIONS = {
  DASHBOARD: [ROLES.SUPER_ADMIN, ROLES.OPERATIONS_ADMIN, ROLES.FINANCE_ADMIN, ROLES.SUPPORT_ADMIN],
  ORDERS: [ROLES.SUPER_ADMIN, ROLES.OPERATIONS_ADMIN, ROLES.SUPPORT_ADMIN],
  RESTAURANTS: [ROLES.SUPER_ADMIN, ROLES.OPERATIONS_ADMIN],
  DELIVERY_BOYS: [ROLES.SUPER_ADMIN, ROLES.OPERATIONS_ADMIN],
  CUSTOMERS: [ROLES.SUPER_ADMIN, ROLES.SUPPORT_ADMIN],
  FINANCE: [ROLES.SUPER_ADMIN, ROLES.FINANCE_ADMIN],
  MARKETING: [ROLES.SUPER_ADMIN, ROLES.OPERATIONS_ADMIN],
  REPORTS: [ROLES.SUPER_ADMIN, ROLES.FINANCE_ADMIN, ROLES.OPERATIONS_ADMIN],
  SUPPORT: [ROLES.SUPER_ADMIN, ROLES.SUPPORT_ADMIN, ROLES.OPERATIONS_ADMIN],
  SETTINGS: [ROLES.SUPER_ADMIN],
  SYSTEM_LOG: [ROLES.SUPER_ADMIN, ROLES.OPERATIONS_ADMIN],
}

export const hasPermission = (userRole, moduleKey) => {
  if (!userRole) return false
  if (userRole === ROLES.SUPER_ADMIN) return true
  const allowedRoles = PERMISSIONS[moduleKey] || []
  return allowedRoles.includes(userRole)
}
